---
# requirements.yml — Collections Ansible requises
# Installation : ansible-galaxy install -r requirements.yml

collections:
  - name: community.general
    version: ">=9.0.0"
  - name: community.docker
    version: ">=4.0.0"
  - name: community.crypto
    version: ">=2.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.postgresql
    version: ">=3.0.0"
  - name: hetzner.hcloud
    version: ">=4.0.0"

roles: []
