---
# sd-common — handlers

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  become: true
