---
# inventory/hosts.yml — Inventaire Ansible
# Remplir avec les valeurs du wizard (PRD.md section 2)

all:
  children:
    prod:
      hosts:
        prod-server:
          ansible_host: "{{ prod_ip }}"
          ansible_port: "{{ prod_ssh_port }}"
          ansible_user: "{{ prod_user }}"
          target_env: "prod"

    preprod:
      hosts:
        preprod-server:
          ansible_host: "{{ preprod_ip | default('127.0.0.1') }}"
          ansible_port: 22
          ansible_user: "root"
          target_env: "preprod"

    vpn:
      hosts:
        vpn-server:
          ansible_host: "{{ vpn_headscale_ip }}"
          ansible_port: 22
          ansible_user: "{{ prod_user }}"
          target_env: "vpn"

  vars:
    ansible_python_interpreter: /usr/bin/python3
