---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: flash-suite-test
    image: geerlingguy/docker-debian12-ansible:latest
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
provisioner:
  name: ansible
verifier:
  name: ansible
