---
galaxy_info:
  role_name: obsidian
  author: VPAI
  namespace: mobutoo
  description: Deploy CouchDB and Obsidian vault sync
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie

dependencies: []
