---
galaxy_info:
  role_name: app_scaffold
  author: VPAI
  namespace: mobutoo
  description: Base infrastructure for App Factory apps on Hetzner
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie

dependencies: []
