#!/bin/bash
# test_secret_run.sh — TDD RED-phase suite for secret-run (Task 7, plan
# docs/superpowers/plans/2026-07-16-vaultwarden-p0-p1b.md lignes 74-95).
#
# Hermetic: never touches the real coffre (Vaultwarden/rbw config) or network.
# A fake `rbw` (and a fake child command, `child-helper`) are generated at
# runtime into a throwaway bin dir prepended to PATH; a self-check aborts the
# WHOLE run (before any of the 9 tests) if that shadowing did not take effect.
#
# secret-run does not exist yet (or is an always-failing stub) — ALL 9 TESTS
# MUST FAIL. This file exists to define secret-run's contract (TDD).
#
# Assumed secret-run CLI contract (encoded by these tests, to be implemented
# in Step 3 of Task 7 — NOT part of this RED-phase commit):
#   Usage: secret-run <REF> -- <cmd> [args...]
#   - REF is looked up in the policy file at $SECRET_RUN_POLICY (env override;
#     production default would be /etc/secret-run/politique.yml).
#   - Policy format (YAML): top-level key = REF, value has a `commands:` list
#     of allowed executable basenames for that REF.
#   - The secret value is fetched via `rbw get <REF>` (resolved through PATH,
#     so it MUST be swappable for a fake).
#   - The secret is exported into the child's environment under the env var
#     name REF (e.g. ref MACGYVER_BOT_TOKEN -> child sees $MACGYVER_BOT_TOKEN),
#     NEVER as a CLI argument to the child, NEVER visible in the child's own
#     /proc/<pid>/cmdline.
#   - Exit codes: 2 = policy denial (ref unknown to policy, OR command not
#     allowed for that ref) — checked BEFORE any rbw call. Non-zero and != 2 =
#     vault error (ref not found in vault, or vault locked) with a clear
#     message on stderr, fail-closed (no child spawned, no empty value
#     injected). Any other case: the child's own exit code is propagated
#     unchanged.
#   - stdout/stderr relayed from the child are scanned and every occurrence of
#     the fetched secret value is replaced by the literal string [REDACTED]
#     before being relayed on secret-run's own stdout/stderr.
#   - If $SECRET_RUN_AUDIT_LOG is set, secret-run appends one line per
#     invocation to that file; the line MUST reference the ref/result and
#     MUST NEVER contain the raw secret value.
#
# Usage: bash test_secret_run.sh
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SECRET_RUN_BIN="$HERE/secret-run"

TMPROOT="$(mktemp -d)"
trap 'rm -rf "$TMPROOT"' EXIT

FAKE_BIN="$TMPROOT/bin"
POLICY_FILE="$TMPROOT/politique.yml"
mkdir -p "$FAKE_BIN"

# --- secret values used by the fixtures (never real, never printed except by
#     the test doubles themselves for assertion purposes) ---
SECRET_VAL_OK="SR-TEST-SECRET-9f3a1c7e"

# --- fake rbw: hermetic stand-in, simulates a 2-entry vault + a lock switch ---
cat > "$FAKE_BIN/rbw" <<EOF
#!/bin/bash
# fake-rbw — test double for test_secret_run.sh ONLY. Never touches the real
# vault, rbw config dir, or network.
set -euo pipefail
cmd="\${1:-}"
ref="\${2:-}"
if [ "\$cmd" != "get" ]; then
  echo "fake-rbw: unsupported subcommand '\$cmd' (test double only supports get)" >&2
  exit 64
fi
if [ "\${FAKE_RBW_LOCKED:-0}" = "1" ]; then
  echo "fake-rbw: error: the store is locked, run 'rbw unlock'" >&2
  exit 1
fi
case "\$ref" in
  TEST_REF_OK)
    echo "$SECRET_VAL_OK"
    ;;
  TEST_REF_WRONG_CMD)
    echo "some-other-secret-value"
    ;;
  *)
    echo "fake-rbw: error: no entry found for '\$ref'" >&2
    exit 1
    ;;
esac
EOF
chmod +x "$FAKE_BIN/rbw"

# --- child-helper: inert test-double "child process", mode-dispatched ---
cat > "$FAKE_BIN/child-helper" <<'EOF'
#!/bin/bash
# child-helper — inert test double for a real child command (curl, hcloud...).
# Used only by test_secret_run.sh. Touches no network, no real secret.
set -euo pipefail
mode="${1:-}"
shift || true
case "$mode" in
  env-and-cmdline)
    varname="${1:?varname required}"
    val="${!varname:-<UNSET>}"
    echo "ENV:${val}"
    echo "ARGV:$*"
    printf 'CMDLINE:'
    tr '\0' ' ' < /proc/self/cmdline
    echo
    ;;
  leak-stdout)
    varname="${1:?varname required}"
    val="${!varname:-<UNSET>}"
    echo "secret-leak:${val}"
    ;;
  leak-stderr)
    varname="${1:?varname required}"
    val="${!varname:-<UNSET>}"
    echo "secret-leak:${val}" >&2
    ;;
  exit-with)
    code="${1:?exit code required}"
    exit "$code"
    ;;
  touch-marker)
    path="${1:?marker path required}"
    : > "$path"
    ;;
  *)
    echo "child-helper: unknown mode '$mode'" >&2
    exit 64
    ;;
esac
EOF
chmod +x "$FAKE_BIN/child-helper"

# --- fixture policy: covers allowed ref/cmd, ref-with-restricted-cmd, and a
#     ref that IS in policy but absent from the fake vault. TEST_REF_NOT_IN_POLICY
#     is deliberately NEVER listed. ---
cat > "$POLICY_FILE" <<'EOF'
# politique.yml (TEST FIXTURE — generated by test_secret_run.sh, never the
# production policy, never contains real refs)
TEST_REF_OK:
  commands:
    - child-helper
TEST_REF_WRONG_CMD:
  commands:
    - true
TEST_REF_NOT_IN_VAULT:
  commands:
    - child-helper
EOF

export PATH="$FAKE_BIN:$PATH"

# --- hermetic self-check: abort the WHOLE run (not just one test) if PATH
#     shadowing did not take effect — this must never be silently skipped. ---
resolved_rbw="$(command -v rbw || true)"
if [ "$resolved_rbw" != "$FAKE_BIN/rbw" ]; then
  echo "SETUP FAILURE: PATH does not resolve rbw to the fake ($FAKE_BIN/rbw), got '$resolved_rbw' — refusing to run (would not be hermetic)." >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# tiny test harness
# ---------------------------------------------------------------------------
LAST_RC=0
LAST_STDOUT=""
LAST_STDERR=""
EXTRA_ENV=()

run_secret_run() {
  local out err rc
  out="$(mktemp -p "$TMPROOT")"
  err="$(mktemp -p "$TMPROOT")"
  set +e
  env "${EXTRA_ENV[@]}" SECRET_RUN_POLICY="$POLICY_FILE" "$SECRET_RUN_BIN" "$@" >"$out" 2>"$err"
  rc=$?
  set -e
  LAST_RC="$rc"
  LAST_STDOUT="$out"
  LAST_STDERR="$err"
  EXTRA_ENV=()
}

PASS_COUNT=0
FAIL_COUNT=0
FAIL_REASONS=()

report() {
  local n="$1" desc="$2" ok="$3" reason="${4:-}"
  if [ "$ok" = "1" ]; then
    PASS_COUNT=$((PASS_COUNT + 1))
    echo "[PASS] test $n: $desc"
  else
    FAIL_COUNT=$((FAIL_COUNT + 1))
    FAIL_REASONS+=("test $n ($desc): $reason")
    echo "[FAIL] test $n: $desc"
    echo "       reason: $reason"
  fi
}

contains() { # haystack_file needle
  grep -qF -- "$2" "$1" 2>/dev/null
}

# ---------------------------------------------------------------------------
# Test 1: ref+cmd autorisées -> exit 0, secret dans l'env enfant, ABSENT de
# son argv et de /proc/<pid>/cmdline.
# ---------------------------------------------------------------------------
test_1() {
  run_secret_run TEST_REF_OK -- child-helper env-and-cmdline TEST_REF_OK

  if [ "$LAST_RC" != "0" ]; then
    report 1 "ref+cmd autorisées -> exit 0 + env only" 0 "exit code was $LAST_RC (expected 0); stderr: $(cat "$LAST_STDERR" 2>/dev/null)"
    return
  fi
  if ! contains "$LAST_STDOUT" "ENV:${SECRET_VAL_OK}"; then
    report 1 "ref+cmd autorisées -> exit 0 + env only" 0 "child did not see the secret in its own env (expected 'ENV:${SECRET_VAL_OK}' in stdout: $(cat "$LAST_STDOUT" 2>/dev/null))"
    return
  fi
  if grep '^ARGV:' "$LAST_STDOUT" 2>/dev/null | grep -qF -- "$SECRET_VAL_OK"; then
    report 1 "ref+cmd autorisées -> exit 0 + env only" 0 "secret value leaked into child argv"
    return
  fi
  if grep '^CMDLINE:' "$LAST_STDOUT" 2>/dev/null | grep -qF -- "$SECRET_VAL_OK"; then
    report 1 "ref+cmd autorisées -> exit 0 + env only" 0 "secret value leaked into /proc/<pid>/cmdline of the child"
    return
  fi
  report 1 "ref+cmd autorisées -> exit 0 + env only" 1
}

# ---------------------------------------------------------------------------
# Test 2: secret dans stdout de l'enfant -> [REDACTED] dans la sortie de
# secret-run.
# ---------------------------------------------------------------------------
test_2() {
  run_secret_run TEST_REF_OK -- child-helper leak-stdout TEST_REF_OK

  if contains "$LAST_STDOUT" "$SECRET_VAL_OK"; then
    report 2 "leak stdout -> [REDACTED]" 0 "raw secret value found un-redacted in secret-run's stdout: $(cat "$LAST_STDOUT" 2>/dev/null)"
    return
  fi
  if ! contains "$LAST_STDOUT" "[REDACTED]"; then
    report 2 "leak stdout -> [REDACTED]" 0 "no [REDACTED] marker found in stdout: $(cat "$LAST_STDOUT" 2>/dev/null)"
    return
  fi
  report 2 "leak stdout -> [REDACTED]" 1
}

# ---------------------------------------------------------------------------
# Test 3: idem en stderr -> [REDACTED].
# ---------------------------------------------------------------------------
test_3() {
  run_secret_run TEST_REF_OK -- child-helper leak-stderr TEST_REF_OK

  if contains "$LAST_STDERR" "$SECRET_VAL_OK"; then
    report 3 "leak stderr -> [REDACTED]" 0 "raw secret value found un-redacted in secret-run's stderr: $(cat "$LAST_STDERR" 2>/dev/null)"
    return
  fi
  if ! contains "$LAST_STDERR" "[REDACTED]"; then
    report 3 "leak stderr -> [REDACTED]" 0 "no [REDACTED] marker found in stderr: $(cat "$LAST_STDERR" 2>/dev/null)"
    return
  fi
  report 3 "leak stderr -> [REDACTED]" 1
}

# ---------------------------------------------------------------------------
# Test 4: ref absente de la politique -> exit 2 (rejected before any rbw call).
# ---------------------------------------------------------------------------
test_4() {
  run_secret_run TEST_REF_NOT_IN_POLICY -- true

  if [ "$LAST_RC" != "2" ]; then
    report 4 "ref hors politique -> exit 2" 0 "exit code was $LAST_RC (expected 2); stderr: $(cat "$LAST_STDERR" 2>/dev/null)"
    return
  fi
  report 4 "ref hors politique -> exit 2" 1
}

# ---------------------------------------------------------------------------
# Test 5: commande absente de la politique pour cette ref -> exit 2.
# TEST_REF_WRONG_CMD only allows "true" in the fixture policy; we invoke
# child-helper instead.
# ---------------------------------------------------------------------------
test_5() {
  run_secret_run TEST_REF_WRONG_CMD -- child-helper env-and-cmdline TEST_REF_WRONG_CMD

  if [ "$LAST_RC" != "2" ]; then
    report 5 "cmd hors politique pour la ref -> exit 2" 0 "exit code was $LAST_RC (expected 2); stderr: $(cat "$LAST_STDERR" 2>/dev/null)"
    return
  fi
  report 5 "cmd hors politique pour la ref -> exit 2" 1
}

# ---------------------------------------------------------------------------
# Test 6: ref inexistante dans le (faux) coffre -> exit != 0 (and != 2, to
# distinguish a policy denial from a vault-lookup failure), clear message on
# stderr.
# ---------------------------------------------------------------------------
test_6() {
  run_secret_run TEST_REF_NOT_IN_VAULT -- child-helper env-and-cmdline TEST_REF_NOT_IN_VAULT

  if [ "$LAST_RC" = "0" ]; then
    report 6 "ref absente du coffre -> exit != 0" 0 "exit code was 0 (expected non-zero)"
    return
  fi
  if [ "$LAST_RC" = "2" ]; then
    report 6 "ref absente du coffre -> exit != 0" 0 "exit code was 2 (policy-denial code) — must be distinct from a vault-lookup failure"
    return
  fi
  if [ ! -s "$LAST_STDERR" ]; then
    report 6 "ref absente du coffre -> exit != 0" 0 "stderr is empty — expected a clear message"
    return
  fi
  if ! contains "$LAST_STDERR" "TEST_REF_NOT_IN_VAULT"; then
    report 6 "ref absente du coffre -> exit != 0" 0 "stderr does not mention the ref (not a clear message): $(cat "$LAST_STDERR" 2>/dev/null)"
    return
  fi
  report 6 "ref absente du coffre -> exit != 0" 1
}

# ---------------------------------------------------------------------------
# Test 7: coffre verrouillé (fake rbw exit != 0) -> fail-closed propre : pas
# de crash sale, pas de valeur vide injectée silencieusement (le child ne
# doit JAMAIS être lancé).
# ---------------------------------------------------------------------------
test_7() {
  local marker
  marker="$TMPROOT/test7-child-ran.marker"
  rm -f "$marker"
  EXTRA_ENV=("FAKE_RBW_LOCKED=1")
  run_secret_run TEST_REF_OK -- child-helper touch-marker "$marker"

  if [ "$LAST_RC" = "0" ]; then
    report 7 "coffre verrouillé -> fail-closed" 0 "exit code was 0 (expected failure when the vault is locked)"
    return
  fi
  if [ "$LAST_RC" = "126" ] || [ "$LAST_RC" = "127" ]; then
    report 7 "coffre verrouillé -> fail-closed" 0 "exit code $LAST_RC means secret-run itself could not even be executed (exec-level failure, e.g. binary missing) — that is NOT secret-run handling a locked vault"
    return
  fi
  if [ -e "$marker" ]; then
    report 7 "coffre verrouillé -> fail-closed" 0 "child process WAS spawned despite the vault being locked (marker file was created) — silent empty-value injection risk"
    return
  fi
  if [ ! -s "$LAST_STDERR" ]; then
    report 7 "coffre verrouillé -> fail-closed" 0 "stderr is empty — a locked vault must fail with a clear message, not silently"
    return
  fi
  if contains "$LAST_STDERR" "No such file or directory" || contains "$LAST_STDERR" "Permission denied"; then
    report 7 "coffre verrouillé -> fail-closed" 0 "stderr looks like a shell exec-level failure (binary missing/not executable), not secret-run's own fail-closed handling: $(cat "$LAST_STDERR" 2>/dev/null)"
    return
  fi
  if contains "$LAST_STDERR" "Traceback" || contains "$LAST_STDERR" "unbound variable" || [ "$LAST_RC" -ge 128 ]; then
    report 7 "coffre verrouillé -> fail-closed" 0 "looks like a dirty crash rather than a clean fail-closed error (rc=$LAST_RC): $(cat "$LAST_STDERR" 2>/dev/null)"
    return
  fi
  if ! grep -qiE 'lock|verrouill' "$LAST_STDERR" 2>/dev/null; then
    report 7 "coffre verrouillé -> fail-closed" 0 "stderr never mentions the vault being locked — cannot confirm this is secret-run's own fail-closed handling rather than an unrelated error: $(cat "$LAST_STDERR" 2>/dev/null)"
    return
  fi
  report 7 "coffre verrouillé -> fail-closed" 1
}

# ---------------------------------------------------------------------------
# Test 8: le code de sortie de l'ENFANT est propagé tel quel.
# ---------------------------------------------------------------------------
test_8() {
  run_secret_run TEST_REF_OK -- child-helper exit-with 7

  if [ "$LAST_RC" != "7" ]; then
    report 8 "exit code enfant propagé (7)" 0 "secret-run exited $LAST_RC instead of propagating the child's exit code 7"
    return
  fi
  report 8 "exit code enfant propagé (7)" 1
}

# ---------------------------------------------------------------------------
# Test 9: l'audit JSON (si SECRET_RUN_AUDIT_LOG est fourni) ne contient
# JAMAIS la valeur du secret, seulement la ref et le résultat.
# ---------------------------------------------------------------------------
test_9() {
  local audit_log
  audit_log="$TMPROOT/audit.jsonl"
  rm -f "$audit_log"
  EXTRA_ENV=("SECRET_RUN_AUDIT_LOG=$audit_log")
  run_secret_run TEST_REF_OK -- child-helper env-and-cmdline TEST_REF_OK

  if [ ! -s "$audit_log" ]; then
    report 9 "audit JSON sans la valeur du secret" 0 "no audit log written to \$SECRET_RUN_AUDIT_LOG ($audit_log) even though it was set"
    return
  fi
  if grep -qF -- "$SECRET_VAL_OK" "$audit_log"; then
    report 9 "audit JSON sans la valeur du secret" 0 "the raw secret value was found INSIDE the audit log — critical leak"
    return
  fi
  if ! grep -qF -- "TEST_REF_OK" "$audit_log"; then
    report 9 "audit JSON sans la valeur du secret" 0 "audit log does not reference the ref (TEST_REF_OK) — not a meaningful audit entry: $(cat "$audit_log" 2>/dev/null)"
    return
  fi
  report 9 "audit JSON sans la valeur du secret" 1
}

# ---------------------------------------------------------------------------
# driver
# ---------------------------------------------------------------------------
test_1
test_2
test_3
test_4
test_5
test_6
test_7
test_8
test_9

echo "---"
echo "secret-run RED-phase: $PASS_COUNT/9 passed, $FAIL_COUNT/9 failed"
if [ "$FAIL_COUNT" -gt 0 ]; then
  echo "Failures:"
  for r in "${FAIL_REASONS[@]}"; do
    echo "  - $r"
  done
fi

[ "$FAIL_COUNT" -eq 0 ]
