---
# roles/gotenberg/handlers/main.yml
- name: "Restart gotenberg stack"
  community.docker.docker_compose_v2:
    project_src: "/opt/{{ project_name }}"
    files:
      - docker-compose.yml
    services:
      - gotenberg
    state: present
    recreate: always
  become: true
