---
galaxy_info:
  role_name: plane
  author: VPAI
  namespace: mobutoo
  description: Deploy Plane project management platform
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie

dependencies: []
