---
galaxy_info:
  role_name: workstation_monitoring
  author: VPAI
  namespace: mobutoo
  description: Deploy node_exporter and monitoring agents on the workstation
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie

dependencies: []
