---
galaxy_info:
  role_name: penpot
  author: VPAI
  namespace: mobutoo
  description: Deploy Penpot open-source design and prototyping platform
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie

dependencies: []
