import React from 'react';
import { registerRoot, Composition } from 'remotion';

// Placeholder composition — will be extended in Phase 10.3
const ProductDemo = ({ title, subtitle }) => {
  return React.createElement(
    'div',
    {
      style: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        height: '100%',
        background: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
        color: '#fff',
        fontFamily: 'sans-serif',
      },
    },
    React.createElement('h1', { style: { fontSize: 64 } }, title || 'Product Demo'),
    React.createElement('p', { style: { fontSize: 32, opacity: 0.7 } }, subtitle || 'Generated by Remotion'),
  );
};

const Root = () => {
  return React.createElement(
    React.Fragment,
    null,
    React.createElement(Composition, {
      id: 'ProductDemo',
      component: ProductDemo,
      durationInFrames: 150,
      fps: 30,
      width: 1920,
      height: 1080,
      defaultProps: { title: 'Product Demo', subtitle: 'Generated by Remotion' },
    }),
  );
};

registerRoot(Root);
